### ISSUE TITLE
Screen sizing for game view

### ISSUE THREAD

**Issue by crgallac** [hr-gith/risk_game#1]
@leila-git @hr-gith The map view would benefit from not being set using pixel values and should be scaled proportionally to the view-port size. Tough to see the map on a 4k screen.

**Comment by crgallac** [comment]
Game text prompts should be refined for next build: i.e. "Replace Army" should be "Place army" and maybe a counter showing the number of armies to replace. Saying you have "5 armies to place" etc.

**Comment by hr-gith** [comment]
Hi Colin,

I agree that we should make it much better.
But It’s the last day and it’s better to do it in next build.

**Comment by crgallac** [comment]
Ya of course. I'm making these issues so we can fix them when we refactor. It is part of the process.
